admission/urls.py
from django.urls import path

from . import views

app_name = "admission"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "admission_start", views.admission_start_adminview, name="admission_start_admin"
    ),
    path(
        "departments/<int:department_id>/interviewees",
        views.department_index,
        name="department_index",
    ),
    path(
        "departments/<int:department_id>/interviewees/<int:interviewee_id>",
        views.interviewee_detail,
        name="interviewee_detail",
    ),
    path(
        "departments/<int:department_id>/interviewees/<int:interviewee_id>/admit",
        views.interviewee_admit,
        name="interviewee_admit",
    ),
    path(
        "departments/<int:department_id>/interviewees/<int:interviewee_id>/reject",
        views.interviewee_reject,
        name="interviewee_reject",
    ),
    path(
        "departments/<int:department_id>/admitted",
        views.department_admitted,
        name="department_admitted",
    ),
    path(
        "departments/<int:department_id>/admitted/download_csv",
        views.department_admitted_csv,
        name="department_admitted_csv",
    ),
    path("final_queue", views.final_queue_index, name="final_queue_index"),
    path(
        "final_queue_detail/<int:interviewee_id>/interviewees",
        views.final_queue_detail,
        name="final_queue_detail",
    ),
    path(
        "final_queue_admit/<int:department_id>/<int:interviewee_id>",
        views.final_queue_admit,
        name="final_queue_admit",
    ),
]

interview/urls.py
from django.urls import path

from . import views

app_name = "interview"

urlpatterns = [
    path("", views.index, name="index"),
    path("public", views.public_index, name="public_index"),
    path("interviewer/<int:room_id>", views.interviewer_change_room, name="interviewer_change_room"),
    path("interviewees", views.interviewee_index, name="interviewee_index"),
    path(
        "interviewees/<int:interviewee_id>/checkin",
        views.interviewee_checkin,
        name="interviewee_checkin",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/assign",
        views.interviewee_assign,
        name="interviewee_assign",
    ),
    path("rooms/<int:room_id>/interviewees", views.room_index, name="room_index"),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>",
        views.room_interviewee_detail,
        name="room_interviewee_detail",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/start",
        views.room_interviewee_start,
        name="room_interviewee_start",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/end",
        views.room_interviewee_end,
        name="room_interviewee_end",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/comment",
        views.room_interviewee_comment,
        name="room_interviewee_comment",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/judge",
        views.room_interviewee_judge,
        name="room_interviewee_judge",
    ),
    path(
        "api/interviewees/<int:interviewee_id>/comment",
        views.interviewee_comment_api,
        name="interviewee_comment_api",
    ),
    path(
        "api/interviewees/<int:interviewee_id>/judge",
        views.interviewee_judge_api,
        name="interviewee_judge_api",
    ),
]

interview_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="interview/"), name="index"),
    path("interview/", include("interview.urls")),
    path("admission/", include("admission.urls")),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("api/", include("interview.api_urls")),
]

admission/models.py
from django.db import models

# Create your models here.

interview/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm, Form


class Global(models.Model):
    INTERVIEW = 1
    ADMISSION = 2

    STATUS = (
        (INTERVIEW, "正在进行面试"),
        (ADMISSION, "正在进行录取"),
    )

    name = models.CharField(max_length=20, default="global_config")
    status = models.IntegerField(choices=STATUS, default=INTERVIEW)

    @classmethod
    def get(cls):
        if Global.objects.count() == 0:
            return None
        else:
            return Global.objects.get(pk=1)

    def __str__(self) -> str:
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Interviewer(models.Model):
    WAITING_ROOM = 1
    INTERVIEW_ROOM = 2
    OBSERVER = 3
    INTERVIEW_IDENTITY = (
        (WAITING_ROOM, "候场引导"),
        (INTERVIEW_ROOM, "面试官"),
        (OBSERVER, "围观群众"),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    interview_identity = models.IntegerField(choices=INTERVIEW_IDENTITY)
    department = models.ForeignKey(
        Department, blank=True, null=True, on_delete=models.SET_NULL
    )
    room = models.ForeignKey(Room, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.first_name


class Interviewee(models.Model):
    NOT_CHECKED_IN = 1
    CHECKED_IN = 2
    INTERVIEW_READY = 3
    INTERVIEW_STARTED = 4
    INTERVIEW_END = 5
    FIRST_PREFERENCE_QUEUE = 6
    SECOND_PREFERENCE_QUEUE = 7
    FINAL_QUEUE = 8
    ADMITTED = 9
    INTERVIEWEE_STATUS = (
        (NOT_CHECKED_IN, "未签到"),
        (CHECKED_IN, "已签到候场"),
        (INTERVIEW_READY, "已分配教室准备出发"),
        (INTERVIEW_STARTED, "面试开始"),
        (INTERVIEW_END, "面试结束"),
        (FIRST_PREFERENCE_QUEUE, "第一志愿队列"),
        (SECOND_PREFERENCE_QUEUE, "第二志愿队列"),
        (FINAL_QUEUE, "最终队列"),
        (ADMITTED, "已录取"),
    )
    name = models.CharField(max_length=30)
    sex = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    student_id = models.CharField(max_length=15)
    majar_text = models.CharField(max_length=30)
    introduction_text = models.TextField()
    interview_status = models.IntegerField(choices=INTERVIEWEE_STATUS)
    accept_adjust = models.BooleanField()
    first_preference = models.ForeignKey(
        Department,
        blank=True,
        null=True,
        related_name="first_preference",
        on_delete=models.SET_NULL,
    )
    second_preference = models.ForeignKey(
        Department,
        blank=True,
        null=True,
        related_name="second_preference",
        on_delete=models.SET_NULL,
    )
    admitted_department = models.ForeignKey(
        Department,
        blank=True,
        null=True,
        related_name="admitted_department",
        on_delete=models.SET_NULL,
    )
    assigned_room = models.ForeignKey(
        Room, blank=True, null=True, on_delete=models.SET_NULL
    )
    assigned_datetime = models.DateTimeField()
    start_datetime = models.DateTimeField(blank=True,null=True)
    end_datetime = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.name


class Judgement(models.Model):
    representation = models.TextField()
    ability = models.TextField()
    cognition = models.TextField()

    interviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    interviewee = models.ForeignKey(Interviewee, on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s" % (self.interviewee, self.interviewer.first_name)

class JudgementForm(ModelForm):
    class Meta:
        model = Judgement
        fields = ["representation", "ability", "cognition"]


class Comment(models.Model):
    content = models.TextField()
    interviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    interviewee = models.ForeignKey(Interviewee, on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s" % (self.interviewee, self.interviewer.first_name)


class PartialCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

admission/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.html import escape
from django.db.models import Q
import csv
from interview.models import *


def Forbidden(msg=None):
    if msg is None:
        msg = "If you think that this is a bug, please contact the project maintainer."
    return HttpResponseForbidden(f"<h1>Forbidden</h1><p>{msg}</p><p><button onclick='window.history.back()'>返回</button></p>")


def index(request):
    gconf = Global.get()
    if gconf.status == Global.INTERVIEW:
        return Forbidden(f"当前状态为 <b> {gconf.get_status_display()} </b><br/> 请联系超管更改状态！")
    return render(request, "admission/index.html")


@login_required()
def admission_start_adminview(request):
    if not request.user.is_authenticated or not request.user.is_superuser:
        return Forbidden()
    interviewees = Interviewee.objects.filter(
        interview_status=Interviewee.INTERVIEW_END
    )
    if request.method == "POST":
        interviewees.update(interview_status=Interviewee.FIRST_PREFERENCE_QUEUE)
        gconf = Global.get()
        gconf.status = Global.ADMISSION
        gconf.save()
        return HttpResponse("done")
    interviewee_list = interviewees.all()
    return render(
        request,
        "admission/admission_start_admin.html",
        context={"interviewee_list": interviewee_list},
    )


@login_required()
def department_index(request, department_id):
    user_department_id = request.user.interviewer.department_id
    if user_department_id != department_id:
        return Forbidden()
    department = get_object_or_404(Department, pk=department_id)
    interviewee_list = Interviewee.objects.filter(
        Q(
            first_preference=department,
            interview_status=Interviewee.FIRST_PREFERENCE_QUEUE,
        )
        | Q(
            second_preference=department,
            interview_status=Interviewee.SECOND_PREFERENCE_QUEUE,
        )
    ).all()
    context = {"department_id": department_id, "interviewee_list": interviewee_list}
    return render(request, "admission/department_index.html", context=context)


@login_required()
def department_admitted(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    department_list = Department.objects.all()
    interviewee_list = Interviewee.objects.filter(
        admitted_department=department, interview_status=Interviewee.ADMITTED
    ).all()
    context = {
        "department_id": department_id,
        "interviewee_list": interviewee_list,
        "department_list": department_list,
    }
    return render(request, "admission/department_admitted.html", context=context)


@login_required()
def interviewee_detail(request, department_id, interviewee_id):
    user_department_id = request.user.interviewer.department_id
    if user_department_id != department_id:
        return Forbidden()
    interviewee = get_object_or_404(Interviewee, pk=interviewee_id)
    if (
        interviewee.interview_status < Interviewee.FIRST_PREFERENCE_QUEUE
        or interviewee.interview_status > Interviewee.SECOND_PREFERENCE_QUEUE
    ):
        return Forbidden()
    comment_list = Comment.objects.filter(interviewee=interviewee)
    judgement_list = Judgement.objects.filter(interviewee=interviewee)
    context = {
        "department_id": department_id,
        "interviewee": interviewee,
        "comment_list": comment_list,
        "judgement_list": judgement_list,
    }
    return render(request, "admission/interviewee_detail.html", context=context)


@login_required()
def interviewee_admit(request, department_id, interviewee_id):
    user_department_id = request.user.interviewer.department_id
    if user_department_id != department_id:
        return Forbidden()
    department = get_object_or_404(Department, pk=department_id)
    interviewee = get_object_or_404(Interviewee, pk=interviewee_id)
    if interviewee.interview_status == Interviewee.FIRST_PREFERENCE_QUEUE:
        if interviewee.first_preference != department:
            return Forbidden()
        interviewee.admitted_department = department
        interviewee.interview_status = Interviewee.ADMITTED
        interviewee.save()
    elif interviewee.interview_status == Interviewee.SECOND_PREFERENCE_QUEUE:
        if interviewee.second_preference != department:
            return Forbidden()
        interviewee.admitted_department = department
        interviewee.interview_status = Interviewee.ADMITTED
        interviewee.save()
    else:
        return Forbidden()
    return HttpResponseRedirect(
        reverse("admission:department_index", args=(department_id,))
    )


@login_required()
def interviewee_reject(request, department_id, interviewee_id):
    user_department_id = request.user.interviewer.department_id
    if user_department_id != department_id:
        return Forbidden()
    department = get_object_or_404(Department, pk=department_id)
    interviewee = get_object_or_404(Interviewee, pk=interviewee_id)
    if interviewee.interview_status == Interviewee.FIRST_PREFERENCE_QUEUE:
        if interviewee.first_preference != department:
            return Forbidden()
        if interviewee.accept_adjust:
            interviewee.interview_status = Interviewee.SECOND_PREFERENCE_QUEUE
        else:
            interviewee.interview_status = Interviewee.FINAL_QUEUE
        interviewee.save()
    elif interviewee.interview_status == Interviewee.SECOND_PREFERENCE_QUEUE:
        if interviewee.second_preference != department:
            return Forbidden()
        interviewee.interview_status = Interviewee.FINAL_QUEUE
        interviewee.save()
    else:
        return Forbidden()
    return HttpResponseRedirect(
        reverse("admission:department_index", args=(department_id,))
    )


@login_required()
def final_queue_index(request):
    interviewee_list = Interviewee.objects.filter(
        interview_status=Interviewee.FINAL_QUEUE
    ).all()
    context = {"interviewee_list": interviewee_list}
    return render(request, "admission/final_queue_index.html", context=context)


@login_required()
def final_queue_detail(request, interviewee_id):
    department = request.user.interviewer.department
    interviewee = get_object_or_404(Interviewee, pk=interviewee_id)
    comment_list = Comment.objects.filter(interviewee=interviewee)
    context = {
        "interviewee": interviewee,
        "department": department,
        "comment_list": comment_list,
    }
    return render(request, "admission/final_queue_detail.html", context=context)


@login_required()
def final_queue_admit(request, department_id, interviewee_id):
    user_department_id = request.user.interviewer.department_id
    department = get_object_or_404(Department, pk=department_id)
    interviewee = get_object_or_404(Interviewee, pk=interviewee_id)
    if user_department_id != department_id:
        return Forbidden()
    if interviewee.interview_status != Interviewee.FINAL_QUEUE:
        return Forbidden()
    interviewee.admitted_department = department
    interviewee.interview_status = Interviewee.ADMITTED
    interviewee.save()
    return HttpResponseRedirect(reverse("admission:final_queue_index"))


@login_required()
def department_admitted_csv(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    interviewee_list = Interviewee.objects.filter(
        admitted_department=department, interview_status=Interviewee.ADMITTED
    ).all()
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = f"attachment; filename={department.id}.csv"

    writer = csv.writer(response)
    writer.writerow(
        ("name", "sex", "student_id", "phone_number", "admitted_department")
    )
    for it in interviewee_list:
        writer.writerow(
            (it.name, it.sex, it.student_id, it.phone_number, it.admitted_department)
        )
    return response

admission/templates/admission/admission_start_admin.html
<ul>
    {% for interviewee in interviewee_list %}
    <li>
        {{ interviewee.id }} - {{ interviewee.name }} - {{ interviewee.get_interview_status_display }}
    </li>
    {% endfor %}
</ul>


<form action="{% url 'admission:admission_start_admin' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="确认无误，开始录取">
</form>

admission/templates/admission/department_admitted.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>网协面试系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="{% static "interview/bootstrap.min.css" %}" rel="stylesheet">
    <script src="{% static "interview/jquery.min.js" %}"></script>
    <script src="{% static "interview/bootstrap.min.js" %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="#">网协面试系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'interview:index' %}">面试系统</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admission:index'%}">录取系统 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
            </form>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="jumbotron">
            <div class="mb-3">
                <p>
                    {% for department in department_list %}
                    <a href="{% url 'admission:department_admitted' department.id %}">{{ department }}</a>
                    {% endfor %}
                </p>
                <p>
                    <a href="{% url 'admission:department_admitted_csv' department_id %}">下载csv</a>
                    <a href="{% url 'admission:index'%}">返回</a>
                </p>
            </div>
            {% if interviewee_list %}
            <table class="table table-hover table-responsive m-auto">
                <thead>
                    <tr>
                        <th>姓名</th>
                        <th>性别</th>
                        <th>学号</th>
                        <th>状态</th>
                        <th>接受调剂</th>
                        <th>一志愿</th>
                        <th>二志愿</th>
                        <th>录取部门</th>
                    </tr>
                </thead>
                <tbody>
                    {% for interviewee in interviewee_list %}
                    <tr class="warning">
                        <td>{{ interviewee.name }}</td>
                        <td>{{ interviewee.sex }}</td>
                        <td>{{ interviewee.student_id }}</td>
                        <td>{{ interviewee.get_interview_status_display }}</td>
                        <td>{{ interviewee.accept_adjust }}</td>
                        <td>{{ interviewee.first_preference }}</td>
                        <td>{{ interviewee.second_preference }}</td>
                        <td>{{ interviewee.admitted_department }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>还没有人被录取。</p>
            {% endif %}
        </div>
    </main>
</body>

</html>

admission/templates/admission/department_index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>网协面试系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="{% static "interview/bootstrap.min.css" %}" rel="stylesheet">
    <script src="{% static "interview/jquery.min.js" %}"></script>
    <script src="{% static "interview/bootstrap.min.js" %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="#">网协面试系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'interview:index' %}">面试系统</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admission:index'%}">录取系统 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
            </form>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="jumbotron">
            <a href="{% url 'admission:index'%}">返回</a>
            {% if interviewee_list %}
            <table class="table table-hover table-responsive m-auto">
                <thead>
                    <tr>
                        <th>姓名</th>
                        <th>性别</th>
                        <th>学号</th>
                        <th>状态</th>
                        <th>接受调剂</th>
                        <th>一志愿</th>
                        <th>二志愿</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for interviewee in interviewee_list %}
                    <tr class="warning">
                        <td>{{ interviewee.name }}</td>
                        <td>{{ interviewee.sex }}</td>
                        <td>{{ interviewee.student_id }}</td>
                        <td>{{ interviewee.get_interview_status_display }}</td>
                        <td>{{ interviewee.accept_adjust }}</td>
                        <td>{{ interviewee.first_preference }}</td>
                        <td>{{ interviewee.second_preference }}</td>
                        <td>
                        <a href="{% url 'admission:interviewee_detail' department_id interviewee.id %}">
                            <button type="button" class="btn btn-success btn-block">查看</button>
                        </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>还没有人被录取。</p>
            {% endif %}
        </div>
    </main>
</body>

</html>

admission/templates/admission/final_queue_detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>网协面试系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="{% static "interview/bootstrap.min.css" %}" rel="stylesheet">
    <script src="{% static "interview/jquery.min.js" %}"></script>
    <script src="{% static "interview/bootstrap.min.js" %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="#">网协面试系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interview:index' %}">面试系统 </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admission:index'%}">录取系统 <span
                        class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
            </form>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="jumbotron">
            <a href="{% url 'admission:final_queue_index' %}">返回</a>
            <div id="student">
                <table class="table table-hover table-responsive m-auto">
                    <thead>
                        <tr>
                            <th>姓名</th>
                            <th>性别</th>
                            <th>学号</th>
                            <th>专业</th>
                            <th>接受调剂</th>
                            <th>一志愿</th>
                            <th>二志愿</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="warning">
                            <td>{{ interviewee.name }}</td>
                            <td>{{ interviewee.sex }}</td>
                            <td>{{ interviewee.student_id }}</td>
                            <td>{{ interviewee.majar_text }}</td>
                            <td>{{ interviewee.accept_adjust }}</td>
                            <td>{{ interviewee.first_preference }}</td>
                            <td>{{ interviewee.second_preference }}</td>
                            <td>
                                <a href="{% url 'admission:final_queue_admit' department.id interviewee.id %}">
                                    <button type="button" class="btn btn-success btn-block">{{department}} 录取</button>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>


            <div id="comment">
                <div class="mb-5">
                    {% if comment_list %}
                    <ul class="list-group">
                        {% for comment in comment_list %}
                        <li class="list-group-item">{{ comment.interviewer.first_name }}: {{ comment.content }}</li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <ul class="list-group">
                        <li class="list-group-item">还没有评论。</li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
</body>

</html>

admission/templates/admission/final_queue_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="refresh" content="10" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>网协面试系统</title>
    {% load static %}
    <link href="{% static 'interview/bootstrap.min.css' %}" rel="stylesheet" />
    <script src="{% static 'interview/jquery.min.js' %}"></script>
    <script src="{% static 'interview/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">网协面试系统</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'interview:index' %}">面试系统</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admission:index' %}">录取系统 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
          {% csrf_token %}
          <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        <a href="{% url 'admission:index' %}">返回</a>
        <br />
        {% if interviewee_list %}
          <table class="table table-hover table-responsive m-auto">
            <thead>
              <tr>
                <th>姓名</th>
                <th>性别</th>
                <th>学号</th>
                <th>状态</th>
                <th>接受调剂</th>
                <th>一志愿</th>
                <th>二志愿</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {% for interviewee in interviewee_list %}
                <tr class="warning">
                  <td>{{ interviewee.name }}</td>
                  <td>{{ interviewee.sex }}</td>
                  <td>{{ interviewee.student_id }}</td>
                  <td>{{ interviewee.get_interview_status_display }}</td>
                  <td>{{ interviewee.accept_adjust }}</td>
                  <td>{{ interviewee.first_preference }}</td>
                  <td>{{ interviewee.second_preference }}</td>
                  <td>
                    <a href="{% url 'admission:final_queue_detail' interviewee.id %}"><button type="button" class="btn btn-success btn-block">查看</button></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>没有人在这里。</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>