admission/urls.py
from django.urls import path

from . import views

app_name = "admission"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "admission_start", views.admission_start_adminview, name="admission_start_admin"
    ),
    path(
        "departments/<int:department_id>/interviewees",
        views.department_index,
        name="department_index",
    ),
    path(
        "departments/<int:department_id>/interviewees/<int:interviewee_id>",
        views.interviewee_detail,
        name="interviewee_detail",
    ),
    path(
        "departments/<int:department_id>/interviewees/<int:interviewee_id>/admit",
        views.interviewee_admit,
        name="interviewee_admit",
    ),
    path(
        "departments/<int:department_id>/interviewees/<int:interviewee_id>/reject",
        views.interviewee_reject,
        name="interviewee_reject",
    ),
    path(
        "departments/<int:department_id>/admitted",
        views.department_admitted,
        name="department_admitted",
    ),
    path(
        "departments/<int:department_id>/admitted/download_csv",
        views.department_admitted_csv,
        name="department_admitted_csv",
    ),
    path("final_queue", views.final_queue_index, name="final_queue_index"),
    path(
        "final_queue_detail/<int:interviewee_id>/interviewees",
        views.final_queue_detail,
        name="final_queue_detail",
    ),
    path(
        "final_queue_admit/<int:department_id>/<int:interviewee_id>",
        views.final_queue_admit,
        name="final_queue_admit",
    ),
]

interview/urls.py
from django.urls import path

from . import views

app_name = "interview"

urlpatterns = [
    path("", views.index, name="index"),
    path("public", views.public_index, name="public_index"),
    path("interviewer/<int:room_id>", views.interviewer_change_room, name="interviewer_change_room"),
    path("interviewees", views.interviewee_index, name="interviewee_index"),
    path(
        "interviewees/<int:interviewee_id>/checkin",
        views.interviewee_checkin,
        name="interviewee_checkin",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/assign",
        views.interviewee_assign,
        name="interviewee_assign",
    ),
    path("rooms/<int:room_id>/interviewees", views.room_index, name="room_index"),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>",
        views.room_interviewee_detail,
        name="room_interviewee_detail",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/start",
        views.room_interviewee_start,
        name="room_interviewee_start",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/end",
        views.room_interviewee_end,
        name="room_interviewee_end",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/comment",
        views.room_interviewee_comment,
        name="room_interviewee_comment",
    ),
    path(
        "rooms/<int:room_id>/interviewees/<int:interviewee_id>/judge",
        views.room_interviewee_judge,
        name="room_interviewee_judge",
    ),
    path(
        "api/interviewees/<int:interviewee_id>/comment",
        views.interviewee_comment_api,
        name="interviewee_comment_api",
    ),
    path(
        "api/interviewees/<int:interviewee_id>/judge",
        views.interviewee_judge_api,
        name="interviewee_judge_api",
    ),
]

interview_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="interview/"), name="index"),
    path("interview/", include("interview.urls")),
    path("admission/", include("admission.urls")),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("api/", include("interview.api_urls")),
]

interview/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm, Form


class Global(models.Model):
    INTERVIEW = 1
    ADMISSION = 2

    STATUS = (
        (INTERVIEW, "正在进行面试"),
        (ADMISSION, "正在进行录取"),
    )

    name = models.CharField(max_length=20, default="global_config")
    status = models.IntegerField(choices=STATUS, default=INTERVIEW)

    @classmethod
    def get(cls):
        if Global.objects.count() == 0:
            return None
        else:
            return Global.objects.get(pk=1)

    def __str__(self) -> str:
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Interviewer(models.Model):
    WAITING_ROOM = 1
    INTERVIEW_ROOM = 2
    OBSERVER = 3
    INTERVIEW_IDENTITY = (
        (WAITING_ROOM, "候场引导"),
        (INTERVIEW_ROOM, "面试官"),
        (OBSERVER, "围观群众"),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    interview_identity = models.IntegerField(choices=INTERVIEW_IDENTITY)
    department = models.ForeignKey(
        Department, blank=True, null=True, on_delete=models.SET_NULL
    )
    room = models.ForeignKey(Room, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.first_name


class Interviewee(models.Model):
    NOT_CHECKED_IN = 1
    CHECKED_IN = 2
    INTERVIEW_READY = 3
    INTERVIEW_STARTED = 4
    INTERVIEW_END = 5
    FIRST_PREFERENCE_QUEUE = 6
    SECOND_PREFERENCE_QUEUE = 7
    FINAL_QUEUE = 8
    ADMITTED = 9
    INTERVIEWEE_STATUS = (
        (NOT_CHECKED_IN, "未签到"),
        (CHECKED_IN, "已签到候场"),
        (INTERVIEW_READY, "已分配教室准备出发"),
        (INTERVIEW_STARTED, "面试开始"),
        (INTERVIEW_END, "面试结束"),
        (FIRST_PREFERENCE_QUEUE, "第一志愿队列"),
        (SECOND_PREFERENCE_QUEUE, "第二志愿队列"),
        (FINAL_QUEUE, "最终队列"),
        (ADMITTED, "已录取"),
    )
    name = models.CharField(max_length=30)
    sex = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    student_id = models.CharField(max_length=15)
    majar_text = models.CharField(max_length=30)
    introduction_text = models.TextField()
    interview_status = models.IntegerField(choices=INTERVIEWEE_STATUS)
    accept_adjust = models.BooleanField()
    first_preference = models.ForeignKey(
        Department,
        blank=True,
        null=True,
        related_name="first_preference",
        on_delete=models.SET_NULL,
    )
    second_preference = models.ForeignKey(
        Department,
        blank=True,
        null=True,
        related_name="second_preference",
        on_delete=models.SET_NULL,
    )
    admitted_department = models.ForeignKey(
        Department,
        blank=True,
        null=True,
        related_name="admitted_department",
        on_delete=models.SET_NULL,
    )
    assigned_room = models.ForeignKey(
        Room, blank=True, null=True, on_delete=models.SET_NULL
    )
    assigned_datetime = models.DateTimeField()
    start_datetime = models.DateTimeField(blank=True,null=True)
    end_datetime = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.name


class Judgement(models.Model):
    representation = models.TextField()
    ability = models.TextField()
    cognition = models.TextField()

    interviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    interviewee = models.ForeignKey(Interviewee, on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s" % (self.interviewee, self.interviewer.first_name)

class JudgementForm(ModelForm):
    class Meta:
        model = Judgement
        fields = ["representation", "ability", "cognition"]


class Comment(models.Model):
    content = models.TextField()
    interviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    interviewee = models.ForeignKey(Interviewee, on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s" % (self.interviewee, self.interviewer.first_name)


class PartialCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

interview/templates/interview/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>网协面试系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link href="{% static 'interview/bootstrap.min.css' %}" rel="stylesheet" />
    <script src="{% static 'interview/jquery.min.js' %}"></script>
    <script src="{% static 'interview/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">网协面试系统</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'interview:index' %}">面试系统 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admission:index' %}">录取系统</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
            </li>
          </ul>

          <div class="dropdown mr-2">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">切换面试教室</button>
            <div class="dropdown-menu">
              {% for room in room_list %}
                <a class="dropdown-item" href="{% url 'interview:interviewer_change_room' room.id %}">{{ room }}</a>
              {% endfor %}
            </div>
          </div>
          <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
          </form>
        {% else %}
          <ul class="navbar-nav mr-auto"></ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_authentication_init' %}">
            <button class="btn btn-info my-2 my-sm-0" type="submit">登录</button>
          </form>
        {% endif %}
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        {% if user.is_authenticated %}
          <p>欢迎进入网协面试系统，<b>{{ user.first_name }}</b>。</p>
          {% if user.interviewer %}
            <p>
              您的部门是 <b>{{ user.interviewer.department }}</b>。
              <br />
              您的身份是 <b>{{ user.interviewer.get_interview_identity_display }}</b> 位于房间 <b>{{ user.interviewer.room }}</b>。
              <br />
              上述信息若有错误请联系管理员更正。
            </p>
            <p>
              <a href="{% url 'interview:interviewee_index' %}">进入 候场教室</a>
            </p>
            {% for room in room_list %}
              <p>
                <a href="{% url 'interview:room_index' room.id %}">进入 面试教室 - {{ room }}</a>
              </p>
            {% endfor %}
          {% else %}
            <p>您在系统中没有面试身份（interview_identity），请联系管理员设置。</p>
          {% endif %}
        {% else %}
          <p>请使用网协通行证登录系统。</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>

interview/templates/interview/public_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="refresh" content="5" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>网协面试系统</title>
    {% load static %}
    <link href="{% static 'interview/bootstrap.min.css' %}" rel="stylesheet" />
    <script src="{% static 'interview/jquery.min.js' %}"></script>
    <script src="{% static 'interview/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <main role="main" class="container">
      <div>
        {% if interviewee_list %}
          <table class="table table-hover table-responsive m-auto">
            <thead>
              <tr>
                <th>时间</th>
                <th>姓名</th>
                <th>状态</th>
                <th>教室</th>
              </tr>
            </thead>
            <tbody>
              {% for interviewee in interviewee_list %}
                <tr class="warning">
                  <td>{{ interviewee.assigned_datetime|date:'Y-m-d H:i:s' }}</td>
                  <td>{{ interviewee.name }}</td>
                  <td>
                    <button type="button" class="btn btn-success btn-block">{{ interviewee.get_interview_status_display }}</button>
                  </td>
                  <td>{{ interviewee.assigned_room }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>还没有面试者。</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>

interview/templates/interview/room_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="refresh" content="5" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>网协面试系统</title>
    {% load static %}
    <link href="{% static 'interview/bootstrap.min.css' %}" rel="stylesheet" />
    <script src="{% static 'interview/jquery.min.js' %}"></script>
    <script src="{% static 'interview/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">网协面试系统</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'interview:index' %}">面试系统 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admission:index' %}">录取系统</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
          {% csrf_token %}
          <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        <a href="{% url 'interview:index' %}">返回</a>
        {% if interviewee_list %}
          <table class="table table-hover table-responsive m-auto">
            <thead>
              <tr>
                <th>签到时间</th>
                <th>姓名</th>
                <th>性别</th>
                <th>学号</th>
                <th>状态</th>
                <th>接受调剂</th>
                <th>一志愿</th>
                <th>二志愿</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {% for interviewee in interviewee_list %}
                <tr class="warning">
                  <td>{{ interviewee.assigned_datetime|date:'Y-m-d H:i:s' }}</td>
                  <td>{{ interviewee.name }}</td>
                  <td>{{ interviewee.sex }}</td>
                  <td>{{ interviewee.student_id }}</td>
                  <td>{{ interviewee.get_interview_status_display }}</td>
                  <td>{{ interviewee.accept_adjust }}</td>
                  <td>{{ interviewee.first_preference }}</td>
                  <td>{{ interviewee.second_preference }}</td>
                  <td>
                    {% if not readonly %}
                      {% if interviewee.interview_status == 2 %}
                        <a href="{% url 'interview:interviewee_assign' room_id interviewee.id %}"><button type="button" class="btn btn-info btn-block">拉来面试</button></a>
                      {% elif interviewee.interview_status < 5 %}
                        <a href="{% url 'interview:room_interviewee_detail' room_id interviewee.id %}"><button type="button" class="btn btn-warning btn-block">进入面试页面</button></a>
                      {% else %}
                        <a href="{% url 'interview:room_interviewee_detail' room_id interviewee.id %}"><button type="button" class="btn btn-secondary btn-block">填写评论</button></a>
                      {% endif %}
                    {% else %}
                      {% if interviewee.interview_status == 2 %}
                        <button type="button" class="btn btn-secondary btn-block">未分配教室</button>
                      {% else %}
                        <a href="{% url 'interview:room_interviewee_detail' room_id interviewee.id %}"><button type="button" class="btn btn-secondary btn-block">查看</button></a>
                      {% endif %}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>还没有面试者。</p>
        {% endif %}
      </div>
    </main>
  </body>
</html>

interview/templates/interview/room_interviewee_detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>网协面试系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link href="{% static 'interview/bootstrap.min.css' %}" rel="stylesheet" />
    <script src="{% static 'interview/jquery.min.js' %}"></script>
    <script src="{% static 'interview/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">网协面试系统</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'interview:index' %}">面试系统 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admission:index' %}">录取系统</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">管理后台</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'oidc_logout' %}" method="post">
          {% csrf_token %}
          <button class="btn btn-success my-2 my-sm-0" type="submit">注销</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        <a href="{% url 'interview:room_index' room_id %}">返回</a>
        <div id="student">
          <table class="table table-hover table-responsive m-auto text-center">
            <thead>
              <tr>
                <th scope="col">姓名</th>
                <th scope="col">性别</th>
                <th scope="col">学号</th>
                <th scope="col">专业</th>
                <th scope="col">接受调剂</th>
                <th scope="col">一志愿</th>
                <th scope="col">二志愿</th>
                <th scope="col">操作</th>
                <th scope="col">面试计时</th>
              </tr>
            </thead>
            <tbody>
              <tr class="table-warning">
                <td class="align-middle">{{ interviewee.name }}</td>
                <td class="align-middle">{{ interviewee.sex }}</td>
                <td class="align-middle">{{ interviewee.student_id }}</td>
                <td class="align-middle">{{ interviewee.majar_text }}</td>
                <td class="align-middle">{{ interviewee.accept_adjust }}</td>
                <td class="align-middle">{{ interviewee.first_preference }}</td>
                <td class="align-middle">{{ interviewee.second_preference }}</td>
                <td class="align-middle">
                  {% if not readonly %}
                    {% if interviewee.interview_status == 3 %}
                      <a href="{% url 'interview:room_interviewee_start' room_id interviewee.id %}"><button type="button" class="btn btn-success btn-block">开始面试</button></a>
                    {% elif interviewee.interview_status == 4 %}
                      <a href="{% url 'interview:room_interviewee_end' room_id interviewee.id %}"><button type="button" class="btn btn-danger btn-block">结束面试</button></a>
                    {% else %}
                      <button type="button" class="btn btn-secondary btn-block disable">面试已结束</button>
                    {% endif %}
                  {% endif %}
                </td>
                <td class="align-middle">
                  <span id="interview_time">--:--</span>
                </td>
              </tr>
            </tbody>
          </table>
          <ul class="list-group mb-5">
            <li class="list-group-item">{{ interviewee.introduction_text|linebreaksbr }}</li>
          </ul>
        </div>

        <div id="comment">
          <div class="mb-5" id="comment_list_div">
            <!-- for get_interviewee_comments() -->
            <ul class="list-group">
              <li class="list-group-item">正在加载......</li>
            </ul>
          </div>
          {% if not readonly %}
            <form action="{% url 'interview:room_interviewee_comment' room_id interviewee.id %}" method="post" id="comment_form">
              {% csrf_token %}
              <label for="id_content">评论:</label>
              <br />
              <textarea class="form-control" name="content" rows="3" required="" id="id_content"></textarea>
              <br />
              <input type="submit" value="评论" />
            </form>
          {% endif %}
        </div>

        <div id="judge">
          <div class="my-5" id="judge_list_div">
            <ul class="list-group">
              <li class="list-group-item">正在加载......</li>
            </ul>
          </div>
          {% if not readonly %}
            <form action="{% url 'interview:room_interviewee_judge' room_id interviewee.id %}" method="post" id="judge_form">
              {% csrf_token %}
              <label for="id_rep">表达:</label>
              <br />
              <textarea class="form-control" name="representation" rows="2" required="" id="id_rep"></textarea>
              <br />
              <label for="id_abi">能力:</label>
              <br />
              <textarea class="form-control" name="ability" rows="2" required="" id="id_abi"></textarea>
              <br />
              <label for="id_cog">对网协的认识:</label>
              <br />
              <textarea class="form-control" name="cognition" rows="2" required="" id="id_cog"></textarea>
              <br />
              <input type="submit" value="提交评价" />
            </form>
          {% endif %}
        </div>
      </div>
    </main>
  </body>

<script>
var charMap = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
  '/': '&#x2F;',
  '`': '&#x60;',
  '=': '&#x3D;'
};

function escapeHtml(string) {
  return String(string).replace(/[&<>"'`=\/]/g, function (s) {
    return charMap[s];
  });
}

function get_interviewee_comments() {
    const interviewee_id = {{ interviewee.id }};
    $.ajax({
        url: "/api/interviewees/" + interviewee_id + "/comment",
        method: 'GET',
        dataType: 'json',
        success: function(data) {
            let html = '';
            if (data.length == 0) {
                html += '<ul class="list-group"><li class="list-group-item">还没有评论。</li></ul>';
            } else {
                html += '<ul class="list-group">';
                $.each(data, function(index, item) {
                    html += '<li class="list-group-item">' + escapeHtml(item.name) + "：" + escapeHtml(item.content) + '</li>';
                });
                html += '</ul>';
            }
            $('#comment_list_div').html(html);
        },
        error: function(xhr, status, error) {
            const html = '<ul class="list-group"><li class="list-group-item">评论获取错误，请检查网络或联系管理员。</li></ul>';
            $('#comment_list_div').html(html);
        }
    });
}

function get_interviewee_judge() {
  const interviewee_id = {{ interviewee.id }};
  $.ajax({
      url: "/api/interviewees/" + interviewee_id + "/judge",
      method: 'GET',
      dataType: 'json',
      success: function(data) {
          let html = '';
          if (data.length == 0) {
              html += '<ul class="list-group"><li class="list-group-item">还没有评价。</li></ul>';
          } else {
              html += '<ul class="list-group">';
              $.each(data, function(index, item) {
                  html += '<li class="list-group-item">' + escapeHtml(item.name) + "：" + escapeHtml(item.content) + '</li>';
              });
              html += '</ul>';
          }
          $('#judge_list_div').html(html);
      },
      error: function(xhr, status, error) {
          const html = '<ul class="list-group"><li class="list-group-item">评价获取错误，请检查网络或联系管理员。</li></ul>';
          $('#judge_list_div').html(html);
      }
  });
}

function set_formatted_time(start, end){
  var difftime = (end-start)/1000;
  var minutes = parseInt(difftime%3600/60);
  var seconds = parseInt(difftime%60);
  console.log(minutes, seconds);
  $('#interview_time').html(minutes+":"+seconds);
}

function get_interview_time() {
  const start = new Date("{{ interviewee.start_datetime.isoformat }}");
  const now = new Date();
  set_formatted_time(start, now);
}

$("document").ready(function () {
    get_interviewee_comments();
    get_interviewee_judge();
    setInterval(get_interviewee_comments, 1500);

    {% if interviewee.start_datetime is none %}
      $('#interview_time').html("--:--");
    {% else %}
      {% if interviewee.interview_status == 4 %}
        setInterval(get_interview_time, 1000);
      {% else %}
        const start = new Date("{{ interviewee.start_datetime.isoformat }}");
        const end  = new Date("{{ interviewee.end_datetime.isoformat }}");
        set_formatted_time(start, end);
      {% endif %}
    {% endif %}
})

$("#id_content").keydown(function(event){
    event=(event)?event:((window.event) ? window.event : "");
    let keyCode=event.keyCode?event.keyCode:(event.which?event.which:event.charCode);
    let altKey = event.ctrlKey || event.metaKey;
    if(keyCode == 13 && altKey) {
        let newDope=$(this).val()+"\n";
        $(this).val(newDope);
    } else if(keyCode==13) {
        event.preventDefault();
        $("#comment_form").submit()
    }
})

</script>
</html>